# Generated by Django 5.0 on 2024-01-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_sosialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('adresss', models.CharField(max_length=255, verbose_name='adress')),
                ('phones', models.CharField(max_length=255, verbose_name='phones')),
            ],
            options={
                'verbose_name': 'elaqe melumati',
                'verbose_name_plural': 'elaqe melumatlari',
                'ordering': ('-created_at',),
            },
        ),
    ]
