# Generated by Django 5.0 on 2024-01-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_maindetails_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindetails',
            name='locations',
        ),
        migrations.AddField(
            model_name='contact',
            name='locations',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='locations'),
        ),
    ]
