# Generated by Django 5.0 on 2024-01-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='locations',
        ),
        migrations.AddField(
            model_name='contact',
            name='locations',
            field=models.ManyToManyField(to='my_app.location', verbose_name='locations'),
        ),
    ]
