# Generated by Django 5.0 on 2024-01-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_category_name_az_category_name_en_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='locations',
        ),
        migrations.AddField(
            model_name='maindetails',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, to='my_app.location', verbose_name='locations'),
        ),
    ]
