# Generated by Django 5.0 on 2024-01-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_remove_contact_locations_maindetails_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindetails',
            name='locations',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='maindetails',
            name='locations',
            field=models.TextField(blank=True, null=True, verbose_name='locations'),
        ),
    ]
